### ISSUE TITLE
Wrong estimates with ci.reliability

### ISSUE THREAD

**Issue by MarkusTJansen** [yelleKneK/MBESS#1]
Dear Mr. Kelley,

when using the function ci.reliability, the point estimates as well as the CI estimates seem to be off. The result is different from what I would expect when calculating omega seperately.

For what I can see, the problem is that within the final loop of .catOmega, where the respective values of each item pair is summed up. Example: For item pair (1,2) the function should use the thresholds from item 1 and item 2 in

```
for(j in 1:q) {
  for(jp in 1:q) {
    sumprobn2 <- 0
    addprobn2 <- 0
    t1 <- threshold[[j]]       # For item pair (1,2) thresholds of item 1
    t2 <- threshold[[jp]]     # For item pair (1,2) thresholds of item 2, but the ones of item 10 would be used
    for(c in 1:length(t1)) {
      for(cp in 1:length(t2)) {
        sumprobn2 <- sumprobn2 + .p2(t1[c], t2[cp], polyr[j, jp])
        addprobn2 <- addprobn2 + .p2(t1[c], t2[cp], denom[j, jp])
      }
    }
    sumprobn1 <- sum(pnorm(t1))
    sumprobn1p <- sum(pnorm(t2))
    sumnum <- sumnum + (sumprobn2 - sumprobn1 * sumprobn1p)
    addden <- addden + (addprobn2 - sumprobn1 * sumprobn1p)
  }
}
```

However, within the function .getThreshold, result <- list(split(coef$tau, varthres)) the split orders the entries by name which results in the list y1,y10,y11,... etc. instead of y1,y2,y3,...

```
.getThreshold <- function(object) {
  ngroups <- object@Data@ngroups
  coef <- lavaan::inspect(object, "coef")
  result <- NULL
  if(ngroups == 1) {
    targettaunames <- rownames(coef$tau)
    barpos <- sapply(strsplit(targettaunames, ""), function(x) which(x == "|"))
    varthres <- apply(data.frame(targettaunames, barpos - 1), 1, function(x) substr(x[1], 1, x[2]))
    result <- list(split(coef$tau, varthres))
  } else {
    result <- list()
    for(g in 1:ngroups) {
      targettaunames <- rownames(coef[[g]]$tau)
      barpos <- sapply(strsplit(targettaunames, ""), function(x) which(x == "|"))
      varthres <- apply(data.frame(targettaunames, barpos - 1), 1, function(x) substr(x[1], 1, x[2]))
      result[[g]] <- split(coef[[g]]$tau, varthres)
    }
  }
  return(result)
}
```

Therefore for item pair (1,2) the function uses the thresholds from item 1 and item 10 (instead of 1 and 2), but mixes these with e.g. the polychoric correlation of items 1 and 2.

I hope that I was able to explain my problem.

All the best,
Markus Jansen

**Comment by yelleKneK** [comment]
Thanks for finding this (deeply embedded) issue @MarkusTJansen for categorical omega with 10 or more items. Thanks to @bgreenaw for helping me work through this. Updated and fixed in Version 4.8.1.
